env:
  commonjs: true
  es2021: true
  node: true
  jest: true
plugins:
  - jest
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: 12
rules:
  camelcase: error

  # jest
  jest/no-disabled-tests: error
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/prefer-to-have-length: error
