name: 'Prevent merge JIRA Approvals'
description: 'Check labels for convention ending with -required/-approved'
icon: git-merge
color: blue
inputs:
  jira_story_source:
    description: Where to look for the jira story
    required: false
    default: ${GITHUB_REF##*/}
  jira_user:
    description: The email of the jira user.
    required: true
  jira_token:
    description: The API token associated to the user.
    required: true
  jira_url:
    description: The base URL for jira
    required: true
  jira_approve_label:
    description: Which label allows merge
    required: false
    default: 'qa-approved'
  jira_fail_label:
    description: Which label fails a PR
    required: false
    default: 'qa-failed'
runs:
  using: 'node12'
  main: 'dist/index.js'
